### ISSUE TITLE
Champs recherche / Barre de recherche

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#111]
Bug de synchro entre les champs. je fais une recherche alexandre en haut, le lucia reste en bas.

![screenshot 2015-04-27 12 34 21](https://cloud.githubusercontent.com/assets/1215611/7345913/c57317f8-ecd9-11e4-9cf4-73eb709cf2c5.png)

**Comment by Bastorx** [comment]
En même temps ce champ de recherche est destiné à "Ex: Coupe,Brushing..."

Et le second "Qui ?"

Pour moi c'est normal qu'ils soient dissociés, non ?
