### ISSUE TITLE
Google et les urls avec Accents

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#115]
Google plante à mort sur les Urls avec accents

je ne sais pas comment il se retrouve là dessus : http://www.hairfie.com/fr/coiffeurs/V%25C3%25A9lizy~Villacoublay--France

Et il en a beaucoup des comme ça.

**Comment by Bastorx** [comment]
URL Encoding ?

**Comment by ghislaindj** [comment]
Fixed by HairfieApi/4d6ea8d

Il y avait un decodeUri, maintenant il y a un decodeUri et decodeUriComponent
