### ISSUE TITLE
Page réservation d'un salon non réservable

### ISSUE THREAD

**Issue by Herzult** [Hairfie/Website#117]
Lorsqu'un utilisateur arrive sur la page de réservation d'un salon non réservable, indiquer clairmement que le salon n'est pas réservable en ligne pour le moment.

**Comment by ghislaindj** [comment]
"Malheureusement, ce salon ne prend pas de réservation. Pour contacter ce salon, appelez le +33 1 ou envoyez nous un email à hello@hairfie.com"

**Comment by Bastorx** [comment]
Associé au ticket #147.
