### ISSUE TITLE
Lien "(Voir la carte)"  sur les pages coiffeurs ne fonctionnent pas.

### ISSUE THREAD

**Issue by Bastorx** [Hairfie/Website#124]
Sur une page de coiffeur ex: 
http://www.hairfie.com/fr/coiffeur/a6a09869-8767-4fe9-9285-4f9cacf209b3/blonde-by-franck-vidoff

A coté de l'adresse du coiffeur le lien (Voir la carte) se contente de rajouté un #location mais sans modification apparente sur la page.

**Comment by ghislaindj** [comment]
En fait, c'est un lien interne à la page, qui va juste vers la div qui doit avoir l'id location.
Mais visiblement l'ID a été modifié.

Ce qu'ils faut donc faire : 
- si on est sur la page des infos du salon, remettre en place le lien vers la div qui contient bien la map
- si on est sur la page hairfie / avis, revenir vers la page infos du coiffeur avec la div en paramètre.

**Comment by Bastorx** [comment]
Il reste des choses à fixer

**Comment by Bastorx** [comment]
Concrètement ça marche si on est bien sur l'onglet 'information', dans les autres cas ça ne fonctionne pas.

Je ferai une PR pour corriger ça dans la semaine
