### ISSUE TITLE
Bug Extrait de tarifs

### ISSUE THREAD

**Issue by Bastorx** [Hairfie/Website#126]
Sur cette page
http://www.hairfie.com/fr/coiffeur/faef5bab-1148-4dce-ae03-f522aed44353/coiffeur-alexandre-henry

Les extraits de tarifs marqués
: 0€
: 0€

Si les extraits de tarifs sont incomplets il faut une gestion d'erreur pour qu'ils ne soit pas affichés

**Comment by Herzult** [comment]
Intéressant, je crois que pour le coup il va falloir faire un peu de nettoyage en base de données plutôt.



—
Envoyé avec Mailbox

**Comment by Bastorx** [comment]
J'ai améliorer la gestion d'erreur en front sinon pour pas que ça se reproduise meme si la BDD n'est pas à jour
