### ISSUE TITLE
Bouton réserver sur mobile

### ISSUE THREAD

**Issue by Herzult** [Hairfie/Website#129]
Sur mobile, le bouton réserver doit apparaître en bas du premier block d'infos.

**Comment by Bastorx** [comment]
J'ai le droit aux media queries ou vous faites ça autrement ?

**Comment by Bastorx** [comment]
C'est fait,

Je laisse ce ticket ouvert pour un autre problème qui concerne la même page (et quasiment le même CSS), lorsque l'image du Hairfie passe en version mobile, le prix est coupé par le <header>
