### ISSUE TITLE
Sur une page salon non réservable, ne pas afficher le calendrier et le bouton réserver mais le numéro de téléphone.

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#147]
Un exemple de coiffeur non bookable : http://api-staging.hairfie.com/api/businesses/4e950150-7e8d-4044-bea5-7e7d5408fc00

**Comment by Bastorx** [comment]
+ Enlever le bouton réserver sur les BusinessSearchPage des salons non réservables
+ Le bouton Réserver ce salon des HairfiePage renvoie à la BusinessPage

{
phoneNumber: "0145229126",
isBookable: false
}
