### ISSUE TITLE
Quand l'API le précise, afficher le formulaire de resa + le numéro de téléphone en dessous

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#151]
Précisé via le "displayPhoneNumber" ici : http://api-staging.hairfie.com/api/businesses/b499000d-5a55-499f-b66d-a733cb05fb6d

**Comment by Bastorx** [comment]
A voir comment on intègre ça en version mobile

**Comment by Bastorx** [comment]
Je fais ce ticket en parallèles du ticket #147, il y aura une PR pour les 2 issues
