### ISSUE TITLE
Connexion d'un user avec son login mot de passe

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#152]
Créa dispo dans le Drive.

![connect](https://cloud.githubusercontent.com/assets/1215611/8408239/a58a05ca-1e6e-11e5-86de-ede2cca63e54.png)

**Comment by Bastorx** [comment]
Il semble que je n'ai pas l'accès au Drive (je n'en avais pas besoin jusqu'alors (et pas connaissance non plus))

**Comment by Bastorx** [comment]
La créa ci-dessous représente l'inscription pas la connection

D'ailleurs je n'ai pas trouvé de créa pour l'inscription, je vais me débrouiller

**Comment by Bastorx** [comment]
You will need a Facebook App ID before you start using the SDK

Est-ce qu'il y en a déjà une par hasard ?

**Comment by Bastorx** [comment]
On proposera twitter aussi au final ?

**Comment by ghislaindj** [comment]
Pas une priorité non

**Comment by Bastorx** [comment]
Comme c'était dans la créa j'avais préparer un bouton pour lui, j'vais le display: none; au moins il sera déjà présent
