### ISSUE TITLE
Hairfie doit toujours être full width et carré 

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#163]
Lorsqu'on diminue la taille de l'écran sur un HairfiePage, le hairfie dépasse l'écran.

Il faudrait qu'il soit toujours carré et toujours visible entièrement à l'écran.

**Comment by ghislaindj** [comment]
Ce n'est pas corrigé en staging chez moi

**Comment by Bastorx** [comment]
? Pour moi si

http://www-staging.hairfie.com/fr/hairfies/10e-Arrondissement--Paris--France

Les hairfies sont bien carré

**Comment by Bastorx** [comment]
Si il y a une page qui n'affiche pas les Hairfies correctement donne moi le lien

Mais pour moi les Hairfies en staging s'affiche correctement

**Comment by ghislaindj** [comment]
En fait ce ticket parle d'une page ShowHairfiePage du type :
http://www-staging.hairfie.com/fr/hairfie/7eb02bfd-c2af-4f65-8b0f-eba5d8bafde4

Regarde le responsive dessus

2015-07-02 15:43 GMT+02:00 Bastien <notifications@github.com>:

> Si il y a une page qui n'affiche pas les Hairfies correctement donne moi
> le lien
>
> Mais pour moi les Hairfies en staging s'affiche correctement
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hairfie/Website/issues/163#issuecomment-118037761>.
>



-- 
Ghislain de Juvigny
Co-fondateur
ghislain@hairfie.com
+33 6 76 84 49 94 / +33 1 85 08 91 69

**Comment by Bastorx** [comment]
D'accord, moi j'avais travaillé sur les HairfieSearchPage

En faite le Hairfie est bien carré, c'est le backgroud: gris qui donne l'impression que le Hairfie n'est pas carré

D'ailleurs ces bandes grises viennent de l'inté de lucas http://lucasfayolle.com/hairfie/hairfie.html

C'est moi qui ai travaillé dessus je le reprendrai si ça ne va pas

**Comment by Bastorx** [comment]
En effet la div conteneur à une width fixe de 570 px...

Et vu que l'image s'adapte à sa div conteneur

C'est quelques lignes de CSS j'y prendrai pas trop de temps
