### ISSUE TITLE
Page Salon: Avis

### ISSUE THREAD

**Issue by Bastorx** [Hairfie/Website#172]
Pour les utilisateurs connectés, poster un avis sur le salon

- Pas plus d'un certain nombre d'avis / page prévoir un système de pagination
- Si l'utilisateur n'est pas connecter redirigé vers la page de connexion (comme les likes) (à voir)
- Inclure le système de notation allant de 1 à 5 étoiles
- Permettre à l'utilisateur de update son commentaire ou de le supprimer

Voir si l'utilisateur peut rentrer une note sans commentaire

**Comment by Bastorx** [comment]
Je vais démarrer ce ticket

**Comment by ghislaindj** [comment]
Désolé j'étais en réu avec Benjamin, on en reparle lundi matin au calme :-)

On Fri, Sep 11, 2015 at 4:20 PM, Bastien <notifications@github.com> wrote:

> Je vais démarrer ce ticket
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hairfie/Website/issues/172#issuecomment-139559211>.
>



-- 
Ghislain de Juvigny
Co-fondateur
ghislain@hairfie.com
+33 6 76 84 49 94 / +33 1 85 08 91 69
