### ISSUE TITLE
HairfieSearchPage & BusinessSearchPage: Filtre des prix supprimé lors du changement de page

### ISSUE THREAD

**Issue by Bastorx** [Hairfie/Website#175]

**Comment by Bastorx** [comment]
Les tags et catégories restent bien présent dans les query mais pas PriceMin et PriceMax

**Comment by ghislaindj** [comment]
+1 effectivement, bug à ce niveau là.

**Comment by Bastorx** [comment]
+ Ce n'est pas que lors du changement de page, un tags ajouté après un priceFilter supprimera le priceFilter
