### ISSUE TITLE
Page confirmation de résa

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#179]
Concrètement, il faut qu'on revoit cette page en terme de design. Un but serait qu'elle ressemble à ça : 
<img width="605" alt="screenshot 2015-07-22 09 04 49" src="https://cloud.githubusercontent.com/assets/1215611/8820332/c4f43d20-3054-11e5-809c-f3977991d0b7.png">

Il faut donc ajouter : 
- la méthode pour annuler (DELETE sur /:bookingId)
- l'ajout au calendrier (celui là me semble intéressant https://github.com/carlsednaoui/add-to-calendar-buttons)

+ le bouton s'inscrire et le bouton télécharger.

![img_0744](https://cloud.githubusercontent.com/assets/1215611/8821083/2f8e3f2c-305b-11e5-8b45-3874262d87ff.JPG)

**Comment by Bastorx** [comment]
Pour moi il faut ajouter un bouton ou un lien "retour à l'accueil"

- Si la personne est déjà connecté le bouton s'inscrire ne s'affiche évidemment pas

**Comment by Bastorx** [comment]
https://github.com/carlsednaoui/add-to-calendar-buttons

Je suis sensé l'installer comment en fait ?
