### ISSUE TITLE
Profil user : mes avis

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#190]
- Profil user : mes avis
http://api-staging.hairfie.com/v1/businessReviews?filter%5Border%5D=createdAt%20DESC&filter%5Bwhere%5D%5BauthorId%5D=fbeb5aed-a2a9-4842-b177-3c656aea66f5

Attention, utiliser le businessReviewStore pour stocker les reviews.

**Comment by Bastorx** [comment]
Ca me renvoie un tableau vide... pas super pour les tests

**Comment by Bastorx** [comment]
Y a pas mal de soucis coté API sur les avis, j'ai aussi des cas où l'object review renvoyé par l'API n'a pas de business associé
