### ISSUE TITLE
Modification de son profil

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#192]
- Modifier son profil :
=> dans le menu “user"
=> formulaire permettant de modifier les infos déjà réalisées.
=> il faut réaliser une nouvelle page avec une nouvelle url.
=> PUT sur /users/fbeb5aed-a2a9-4842-b177-3c656aea66f5 par exemple

**Comment by Bastorx** [comment]
on fait comment pour les utilisateurs connectés à partir de Facebook ? On peut pas lui faire modifier son mot de passe par exemple, ainsi il faudrait pouvoir différencier un compte FB et normal non ?

**Comment by ghislaindj** [comment]
On fait comme sans FB, on peut modifier ses informations !

**Comment by Bastorx** [comment]
Il y a un soucis coté API,
![capture d ecran 2015-08-06 a 11 28 48](https://cloud.githubusercontent.com/assets/12693066/9108445/64b7923c-3c2e-11e5-9748-bf92c7167680.png)
 422 systématique si on envoie pas toutes les infos. Hors si l'utilisateur ne veut changer quelques infos mais pas son mot de passe (par exemple) on devrait pouvoir envoyer un object juste avec les infos à modifier
