### ISSUE TITLE
Update des packages

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#193]
Update de fluxible et ses dépendances : https://github.com/yahoo/fluxible/blob/master/UPGRADE.md
fluxible router etc...

Un petit npm outdated te donnera d'autres dépendances à mettre à jour, en modifiant le fichier package.json la plupart du temps :-)

**Comment by Bastorx** [comment]
Tous les packets sont mis à jour exepté Watchify, grunt-watchify (qui pointe une branche sur Git), et fluxible-hairfie-api (qui pointe aussi sur git)

**Comment by ghislaindj** [comment]
Good pour le moment
