### ISSUE TITLE
ajouter bouton de téléchargement en web desktop : cf salonist.it + liens téléchargement intelligent en mobile.

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#221]
Sur la homepage en web, ajouter une section avec un lien pour télécharger l'application. https://www.dropbox.com/s/8gcoaxm2wv89fmt/Screenshot%202015-09-14%2023.21.45.png?dl=0

Sur le mobile, ajouter un détecteur qui propose une bannière d'installation intelligente si on est sur iOS

**Comment by Bastorx** [comment]
Comment vois-tu la bannière intelligente (au niveau du style) ?

**Comment by ghislaindj** [comment]
Je veux pas qu'on fasse le design, je veux la bannière officielle d'Apple ici : https://developer.apple.com/library/mac/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html
