### ISSUE TITLE
Hairfies similaires

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#234]
Filtrage Homme / Femme à mettre obligatoire. En fait, si on a un hairfie Homme, on ne veut que des hairfies similaires homme et inversement.

**Comment by Bastorx** [comment]
Sur les hairfies similaires ou sur la hairfieSearchPage ?

**Comment by ghislaindj** [comment]
similaires.

**Comment by Bastorx** [comment]
https://www.algolia.com/doc/node#filter-by-tag
