### ISSUE TITLE
Ajout des labels customs à un salon

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#235]
Nouveau champs dans un business : 
- nom du champs "labels"
exemple "hyper-tendance, hipster, dark" pour un salon
- On ajoute ça dans le webpro
- (later, pas dans ce ticket) : l'idée est de le présenter sous forme de tags plus tard sur une page salon, donc idéalement à stocker en array de strings.

**Comment by Bastorx** [comment]
On défini nous même les labels ? On peut pas laisser le business entrer des labels perosonnalisés ?
