### ISSUE TITLE
Affichage des horaires

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#242]
Bug dans l'affichage des horaires
- L'odyssée de la coiffure affiche ouvert aujourd'hui alors que le salon était déclaré fermé ce jour là (un lundi)
- le second affiche plusieurs fois le même créneau. Il faudrait les réunir quand l'API le fait parvenir.

<img width="1272" alt="screenshot 2015-10-05 15 38 20" src="https://cloud.githubusercontent.com/assets/1215611/10281775/2b10884a-6b77-11e5-9a1b-0c61b55c17bb.png">
<img width="1275" alt="screenshot 2015-10-05 15 38 03" src="https://cloud.githubusercontent.com/assets/1215611/10281776/2bebcca2-6b77-11e5-8ef5-f97ad7204641.png">

**Comment by Bastorx** [comment]
ça me parait bizarre le coup de 14h - 17h / 9h30-19h / 14h - 17h

J'ai pas les accès à la BDD de la prod, une vérification des businesses timeslots s'impose
