### ISSUE TITLE
Liste des résultats : afficher étoiles et pas les notes

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#247]
- [x] Ajouter un bouton se connecter sur formulaire de dépôt d'avis
- [x] Ajouter de formulaire  mot de passe  post dépôt d’avis
- [x] Avis vérifié : à la place de commentaire vérifié
- [x] Liste des avis : augmenter un peu la police (doit être la même que pour les textes)
- [x] Liste des avis : ajouter la note en étoiles
- [x] Formulaire de dépôt d’avis : augmenter la taille
- [x] Wording : impératif partout.
- [x] Bouton déposer un avis sur le Layout et pas uniquement sur l'onglet avis

**Comment by Bastorx** [comment]
## Liste des avis : augmenter un peu la police (doit être la même que pour les textes)

Déjà à la même taille que le texte (font-weight: 1.3em) ?
