### ISSUE TITLE
Page Hairfie

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#266]
Sur la page Hairfie, le multiPhoto est à revoir car peu clair et pas pertinent.

Il faut : 
- [x] qu'on affiche clairement le fait qu'il y ait 2 photos (on peut peut être garder les points blancs), mais il faut ajouter des flèches droites / gauches par exemple
- [x] que ça tienne en mobile
- [x] que les flèches droite / gauche soient infinies (je peux continuer à cliquer sur droite et ça boucle)
- [x] penser à ne rien mettre si 1 seul photo.

En bonus, on pourrait afficher en desktop une miniature du prochain hairfie en bas à droite et en bas à gauche du précédent.

Plusieurs solutions : 
- recleaner le carousel bootstrap (attention au .carousel-control du page-hairfie.scss qui modifie le comportement de base, cf la doc de bootstrap)
- ou bien mettre en place une solution du type slick https://github.com/akiran/react-slick

**Comment by Bastorx** [comment]
Je pense qu'il sera plus simple de recleaner le carousel bootstrap

**Comment by Bastorx** [comment]
Moi je propose une alternative

On passe le carousel de la BusinessPage dans le dossier Partial, et on adapte le css si celui-ci est appelé dans la hairfiepage ou dans la businessPage
