### ISSUE TITLE
Miniature Hairfie

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#267]
Sur la miniature, au hover on pourrait ajouter la seconde photo dans le coin + préciser le nom du salon.

**Comment by Bastorx** [comment]
Le nom du salon c'est à la place de la date si je me rappelle bien

**Comment by ghislaindj** [comment]
Oui, je pense même qu'il faudrait faire : 

Salon : Nom du salon
Coiffeur : Coiffeur

(en soulignant Salon et coiffeur jusqu'aux 2 points)
