### ISSUE TITLE
Ajout d'un bandeau d'inscription à la newsletter

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#270]
L'objectif est d'ajouter un bandeau d'inscription à la newsletter sur une page hairfie ou recherche de hairfie.

Plusieurs choses : 
- Le contenu : Texte + Email + bouton d'action  + croix pour être fermé.
- Module réutilisable (il doit être déjà sur 2 pages)
- Ne s'affiche pas quand on est connecté
- Il faut que quand on le ferme, on note ça dans les cookies pour ne plus l'afficher à la personne. Le cookie doit être différent de celui de la popup.

**Comment by Bastorx** [comment]
Pourquoi uniquement sur la page Hairfie et Recherche d'Hairfie ?
