### ISSUE TITLE
Ajout d'un bloc salons similaires dans la colonne centrale

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#300]
Bloc Salons similaires sur la colonne centrale (sauf premium, attention on évite la requête)

**Comment by Bastorx** [comment]
Sauf premium et basic non ?

**Comment by Bastorx** [comment]
*Pas au même endroit sur basic

**Comment by Bastorx** [comment]
Bloc Hairfie similaire ok

Par contre j'ai suivi à la lettre le Ps, il est activé sur Free uniquement (il peut-être facilement activé pour les 2)

**Comment by Bastorx** [comment]
https://hairfie-website-staging-pr-305.herokuapp.com/fr/coiffeur/000230ea-8998-44b3-bdda-81609d210ce7/jorieux-martine

**Comment by Bastorx** [comment]
Re-déployé
