### ISSUE TITLE
Ajout d'un bloc : les derniers hairfies du salon

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#318]
Présent sur les pages basic + premium
A charger en asynchrone !

**Comment by Bastorx** [comment]
On utilise topBusinesses ?

<code>
    loadBusinessTopHairfies: function (context, businessId) {
        var query = {
            'limit': 6
        };

        return context.hairfieApi
            .get('/tops/hairfies/'+ businessId, { query: query })
            .then(function (hairfies) {
                context.dispatch(Actions.RECEIVE_BUSINESS_TOP_HAIRFIES, {
                    businessId: businessId,
                    hairfies: hairfies
                });
            });
    }
</code>
