### ISSUE TITLE
Changer les icones et la créa du comment ça marche sur la homepage

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#327]
cf Drive UX UI > Release > A mettre en prod

<img width="795" alt="screenshot 2016-01-11 15 37 40" src="https://cloud.githubusercontent.com/assets/1215611/12236305/4c2a90da-b879-11e5-8b45-2ff625b27500.png">

**Comment by Bastorx** [comment]
Peut-être demander à Benoît d'exporter les icônes en sous format SVG ;)
