### ISSUE TITLE
Coiffeurs à France / hairfies à France

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#335]
Mettre un titre dans la base de données pour ces recherches fréquentes.
- "Tous les coiffeurs en France"
- "Tous les hairfies"

**Comment by ghislaindj** [comment]
pour les coiffeurs ça a été fait, à faire pour les hairfies

**Comment by Bastorx** [comment]
Le cache risque de pas affiché la modif correctement

Fix du search utils sur Website
