### ISSUE TITLE
Au scroll sur la recherche mobile

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#338]
J'ai un comportement bizarre où je vois quand même ce qu'il y a en dessous, par exemple le bouton "filtrer" puis au bout de quelques secondes tout se passe bien ...

**Comment by Bastorx** [comment]
J'ai eu le même problème a un moment mais je l'ai fixer dans la journée (PS: N’apparaît pas sur Chrome desktop ou sous Android)

**Comment by ghislaindj** [comment]
On l'a eu dans la dernière version sur iOS sur 3 téléphones différents

**Comment by Bastorx** [comment]
Peux-tu prendre en charge cette issue, il est effectivement présent sur IOS mais n'ayant pas le bon navigateur et pas de quoi virtualiser un IPhone sur cette machine ça m'arrangerai que tu t'en charges
