### ISSUE TITLE
En web, ajouter une seconde navbar noire

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#341]
cf créa : https://www.dropbox.com/s/ruswgkwpbf2r2s6/Screenshot%202016-01-13%2019.09.08.png?dl=0
et https://www.dropbox.com/s/ym4v2w5j3zk451k/Screenshot%202016-01-13%2019.09.25.png?dl=0

**Comment by Bastorx** [comment]
J'ai les psd ;) Je m'en occupe
