### ISSUE TITLE
Retirer le rayon du filtrage des hairfies

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#348]

**Comment by Bastorx** [comment]
On le retire sans rien mettre à la place ?

**Comment by ghislaindj** [comment]
oui

On Mon, Jan 18, 2016 at 4:51 PM, Bastien <notifications@github.com> wrote:

> On le retire sans rien mettre à la place ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hairfie/Website/issues/348#issuecomment-172567590>.
>



-- 
--

Ghislain de Juvigny
Co-fondateur
ghislain@hairfie.com
+33 6 76 84 49 94 / +33 1 85 08 91 69

[image: 💈] Vous cherchez un coiffeur ou vous voulez prendre RDV chez votre
coiffeur habituel ? Allez sur www.hairfie.com
<http://www.hairfie.com/fr/?utm_source=email_ghislain&utm_medium=email&utm_campaign=email_ghislain>
✂ Vous êtes allé récemment chez le coiffeur ? Déposez un avis sur
www.hairfie.com
<http://www.hairfie.com/fr/?utm_source=email_ghislain&utm_medium=email&utm_campaign=email_ghislain>
N'hésitez pas à nous faire des retours sur l'expérience :-)

**Comment by Bastorx** [comment]
https://github.com/Hairfie/Website/commit/171db46984e7e147e84434b5c795f295b7ff5d8a
