### ISSUE TITLE
Texte du bouton "trouver votre coiffeur" qui dépasse sur la Home

### ISSUE THREAD

**Issue by Taskim** [Hairfie/Website#355]
<img width="585" alt="capture d ecran 2016-01-18 a 14 02 46" src="https://cloud.githubusercontent.com/assets/14927805/12392181/55482cf8-bded-11e5-9b14-4bd0cafa13ca.png"> 

... en réduisant la taille de l'écran

**Comment by Bastorx** [comment]
#311
