### ISSUE TITLE
Filtrage ouverture par jour

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#359]
Filtrage par jour d'ouverture.

- Côté API : ajouter un "openOnMonday" etc... au niveau du searchDocument 
- puis ajouter côté indexation algolia (prod + staging)
- puis en facet filter
- et en enfin sur les requêtes API

Puis en front, dans un temps je rajouterai juste 2 cases "ouvert le dimanche", "ouvert le lundi" dans les filtres (à voir avec Benoit sinon avant).

**Comment by Bastorx** [comment]
Sinon on peut se servir de la timetable déjà existante non ?
