### ISSUE TITLE
Recherche de salons : afficher les tags correspondant à la recherche dans les résultats de recherche

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#375]
Exemple : je cherche barbier, je veux un tag "barbier" sur chaque salon qui est effectivement classé barbier.

Idem pour barbier + homme, je veux les 2.

A réfléchir pour voir l'intégration API.

**Comment by Bastorx** [comment]
#373 ?

**Comment by ghislaindj** [comment]
hum, oui c'est exactement ça ;-)
