### ISSUE TITLE
Dépôt d'avis

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#497]
Fichier : usercase-reviews.jpg

CAS 1 : non connecté.
=> on affiche le formulaire entier

CAS 2 : post hairfie
http://www-staging.hairfie.com/fr/deposer-un-avis/?requestId=zFmJ5G1465GHIkSZ9UvLX8lgK65LKr3vjyuqJGHwN5T5x0X23zo88J9gfTNEaiOd&businessId=40b1e699-361d-4713-ba60-e2d60fdd8d65
=> on affiche le formulaire avec email pré rempli (mais je peux modifier l'email)

CAS 3 : post résa 
exemple : http://www-staging.hairfie.com/fr/deposer-un-avis/?requestId=YRQP1n3hY1dbLcfHkTKD4mAUzTWnJhT9yHhuPZX8eNgZe24wv1iL0gCvf2N84mhQ&businessId=4fb783e4-a924-457a-a90f-23ea072a3bab
=> on affiche pas du tout le formulaire, mais les infos partent en direct

**Comment by Taskim** [comment]
Que fait-on dans le cas où l'utilisateur est connecté et que le mail de la résa est différent de celui de son compte ?
