### ISSUE TITLE
Loadmore hairfies

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#533]
Les params de l'API appelée est pageSize=14&page=3.857142857142857&sort=numLikes

Gros bug sur le numéro de page qui fait planter la page.

**Comment by Taskim** [comment]
Comment fais-tu pour obtenir cette url ?

**Comment by ghislaindj** [comment]
elle est appelée régulièrement en cliquant 2/3 fois sur le loadmore. Je pense que c'est parce que certaines pages ne sont pas complètes (tu n'as pas tous les hairfies).
Au besoin, il faudrait s'assurer qu'on utilise bien un entier et pas un decimal.

**Comment by Taskim** [comment]
J'ai rajouté un Math.round() dans le store, même si je n'arrive pas à reproduire le bug sur ma machine. Je pense que ça devrait suffir à régler le problème.
En revanche, on a un key={item.id} qui pose parfois (je ne sais pas en fonction de quoi ça passe ou pas) problème, dans le chargement alterné de hairfies et de business.
