### ISSUE TITLE
Page "Hairfie" : Afficher les autres hairfies du salon

### ISSUE THREAD

**Issue by Herzult** [Hairfie/Website#68]

**Comment by ghislaindj** [comment]
Créa : http://lucasfayolle.com/hairfie/hairfie.html

Wording : "Autres hairfies du même salon"

Penser à ajouter les hairfies petit à petit (comme sur la page coiffeur).

**Comment by Bastorx** [comment]
On a déjà les Hairfies similaires à la place est-ce vraiment nécessaire ?
