### ISSUE TITLE
Page Salon : Ajout de boutons de partages Facebook & Twitter

### ISSUE THREAD

**Issue by ghislaindj** [Hairfie/Website#79]

**Comment by Bastorx** [comment]
Ce ticket est le même que le ticket n°97, sauf que celui-ci est plus complet

**Comment by Herzult** [comment]
Celui-ci concerne la page d'un salon (ex http://www.hairfie.com/fr/coiffeur/fc4b368a-d1e7-4319-84cb-f1e494dacc71/adriano-ns-coiffure)

**Comment by Bastorx** [comment]
D'accord, mais il marche sur le même principe que le ticket 97 non ?

Mais je comprend la différence, je pensais que ces 2 tickets traitaient du même pb.

**Comment by Bastorx** [comment]
Je suppose qu'on peut aussi ajouté Google+, Pinterest et Mail ?

**Comment by ghislaindj** [comment]
Non ce n'est pas exactement le même. En fait pour celui là, il y avait une créa & inté que tu peux voir ici : http://lucasfayolle.com/hairfie/salon.html

En fait de ce côté il y a une page salon, donc pas exemple Pinterest ça n'a pas d'intérêt vu que c'est une image que tu partages, google + et mail pourquoi pas, mais il faudrait le caler dans la créa.

**Comment by Bastorx** [comment]
Le ticket 79 a été mergé au ticket 97 pour changer la classe des deux boutons en même temps et vérifier la cohérence de ces modifications.
